// CALCULATOR PROGRAM

const display = document.getElementById("display");

function appendToDisplay(input){
    display.value += input;
}

function clearDisplay(){
    display.value = "";
}

function calculate(){
    if (!display.value) {
        return;
    }

    try {
        display.value = eval(display.value);
    } catch (error) {
        display.value = "Midrel Pidor";
        setTimeout(() => {
            display.value = "";
        }, 1000);
    }
}